name: Code Coverage


on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


permissions:
  contents: read

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Harden Runner
      uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
      with:
        egress-policy: audit

    - name: Checkout Code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    # Set up dependencies
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y lcov

    # Build the project with coverage flags
    - name: Build with Coverage
      run: |
        cmake -DCMAKE_BUILD_TYPE=Debug -B build
        cmake --build build

    # Run tests
    - name: Run Tests
      run: |
        cd build
        ctest --output-on-failure

    # Generate coverage report
    - name: Generate Coverage Report
      run: |
        lcov --capture --directory build --output-file coverage.info --ignore-errors mismatch,empty
        lcov --remove coverage.info '/usr/*' 'gtest/*' --output-file coverage.filtered.info
        genhtml coverage.filtered.info --output-directory coverage_html

    # Upload to Codecov
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@1e68e06f1dbfde0e4cefc87efeba9e4643565303 # v5.1.2
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        files: coverage.filtered.info
        flags: unittests
        name: code-coverage
        fail_ci_if_error: true

